name: Setup
inputs:
  os:
    required: true
    type: string
  setup:
    required: true
    type: string
runs:
  using: 'composite'
  steps:
    - name: Update OS (deps)
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get -qq update
        sudo apt-get -y install gcc-multilib g++-multilib freeglut3-dev freeglut3-dev:i386 libxrandr-dev libxrandr-dev:i386
      shell: bash
      if: inputs.os == 'linux'
    - name: Set ORX environment variable
      run: echo ORX=%CD%\code>> %GITHUB_ENV%
      shell: cmd
      if: inputs.os == 'windows'
    - name: Cache extern
      uses: actions/cache@v4
      with:
        path: cache
        key: orx-extern
    - name: Setup
      run: ./${{inputs.setup}}
      shell: bash
