#define KZ_MSG_MODE_INIT_FAILED_III       "\n*** Echec de l'initialisation du mode %dx%d (%d bits) ***\n"
#define KZ_MSG_MODE_INIT_SUCCESS_III      "\n*** Mode graphique initialisé en %dx%d (%d bits) ***\n"
#define KZ_MSG_MODE_PAGEFLIP_FAILED       "\n*** Echec de l'initialisation du mode \"page flip\" ***\n"
#define KZ_MSG_MODE_DOUBLEBUFFER_FAILED   "\nEchec de l'initialisation du double buffer!\n"
#define KZ_MSG_NO_MODE_FOUND              "\n*** Aucun mode graphique correct n'a été trouvé!!! ***\n"
