#define MSG_PLUGIN_KZ_INVALID_FILENAME "Le nom de fichier donné est invalide.\n"
#define MSG_PLUGIN_KZ_INVALID_NAME "Le nom de plugin donné est invalide.\n"
#define MSG_PLUGIN_KZ_LOAD_FAILED_Z "Le chargement du plugin <%s> a échoué!\n"
#define MSG_PLUGIN_KZ_MALLOC_FAILED "La tentative d'allocation de la mémoire a échoué!\n"
#define MSG_PLUGIN_KZ_NOT_FOUND "Le plugin demandé n'est pas chargé.\n"
#define MSG_PLUGIN_KZ_FUNCTION_NOT_FOUND "La fonction demandée n'a pas été trouvée.\n"
#define MSG_PLUGIN_KZ_BAD_PARAMETERS "Les paramètres passés à la fonction sont incorrects.\n"
#define MSG_PLUGIN_KZ_DEFAULT_NOT_LOADED_ZZI "La fonction <%s() - %s:%ld> a été appelée avant d'avoir été chargée!\nVérifiez que le plugin correspondant a été chargé et qu'il contient bien cette fonction.\n"
#define MSG_PLUGIN_KZ_NOT_READY "Le mécanisme de plugin n'a pas été initialisé! Appelez la fonction \"plugin_init\" avant toute chose!\n"
