#define KZ_FILE_NO_SEARCH_FOUND "Impossible de récupérer les infos de cette recherche... pas de reecherche en cours"
#define KZ_FILE_READ_SEARCH_ERROR "Un problème de lecture est apparue. Etes vous sur de bien avoir démarré une recherche ??"
#define KZ_FILE_CANT_REMOVE_SEARCH "Impossible de supprimer cette recherche... pas de recherche en cours"
#define KZ_FILE_ONE_SEARCH_FOUND "une seule recherche trouvée"
#define KZ_FILE_REMOVING_SEARCH "suppression de la recherche"
#define KZ_FILE_NO_MATCHING_ID "Une recherche à bien été enregistrée mais son ID ne correspond pas à celle que vous tentez de supprimer. Opération annulée. Effet : perte de mémoire!"
#define KZ_FILE_MULTIPLE_SEARCH_FOUND "Plusieurs recherches trouvées"
#define KZ_FILE_SEARCH_FINISHED "Recherche terminé"
#define KZ_FILE_CANT_REMOVE_FILE "Impossible d'effacer le fichier"
#define KZ_FILE_CANT_RENAME_FILE "Impossible de renomer le fichier"
#define KZ_FILE_SOURCE_orxNULL "Le nom du fichier source est orxNULL"
#define KZ_FILE_DESTINATION_orxNULL "Le nom du fichier de destination est orxNULL"
#define KZ_FILE_DIRECTORY_orxNULL "Le nom du répertoire est orxNULL"
#define KZ_FILE_CANT_CREATE_DIR "Impossible de créer le répertoire"
#define KZ_FILE_CANT_REMOVE_DIR "Impossible d'efface le répertoire"
#define KZ_FILE_REMOVE_RECURSIVELY "Une erreur est apparu pendant la tetative de suppression recursive du répertoire"
#define KZ_FILE_CANT_GET_CWD "Impossible de récupérer le répertoire de travail courant. (peut être le buffer est il trop petit?"

